services:
  - type: web
    name: emotional-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python chatbot.py"
    envVars:
      - key: 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
        sync: false