services:
  - type: web
    name: emotional-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    plan: free
    startCommand: gunicorn chatbot:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false