services:
  - type: web
    name: emotional-chatbot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python chatbot.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false