services:
  - type: web
    name: emotional-chatbot
    env: python
    pythonVersion: 3.10.12 
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot:app
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false